# Site settings
title: echo("桑小凯"); 
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "我只是一个想做大事的开发者"  
baseurl: ""
publicurl:"public"
url: "https://sangxiaokai.github.io"  

# About/contact
owner: 
  name: " 桑小凯 qq 307060248"
  email: 307060248@qq.com
  bio: "有些人只是想得太多做的太少"

# Data
gavatar: https://avatars0.githubusercontent.com/u/3350034?v=4&s=460
favicon: img/favicon.ico


github_username: sangxiaokai


# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CNFeat"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  duoshuo :
    short_name : cnfeat
  disqus :
      short_name : cnfeat

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation